version: '2.1'
services:
  nginx:
    image: 'nginx:latest'
    container_name: nginx_proxy
    ports:
      - ${HTTP_PORT}:8000
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/app.conf

  web:
    image: inowas/knowledgebase
    restart: always
    command: 'bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn explorer.wsgi -b 0.0.0.0:8000"'
    depends_on:
      - db
    volumes:
      - ${DJANGO_SOURCE_FOLDER}/src:/src
      - static-files:/static
      - media-files:/media
    env_file:
      - .env

  db:
    image: mdillon/postgis
    restart: always
    volumes:
        - postgis-data:/var/lib/postgresql/data

volumes:
    postgis-data:
        driver: local
    static-files:
        driver: local
    media-files:
        driver: local
